### PR TITLE
Update led_cube.py

### PR DESCRIPTION
**Pull request by manuelp73**
I have modified it so that it works with newer Python compilers.

### CODE REVIEW

**Comment by bradytheinventor** [comment]
This project is pretty old and not in active development anymore. It's actually a rewrite of a rebuild of a hobby project from 2013. The code here was written in python 2.7 to run on the original Raspberry Pi model B; since the project is not in active development I want to leave it as-is for the most part.

If you can make this pull request backwards compatible with python 2.7 (like by importing things from `__future__`) then I'll accept it, but right now the changed code only works for python 3 and I don't want to have to update any pieces of the project because everything is so old.

**Comment by manuelp73** [comment]
Ok, do you have any idea if anything else needs to be changed to make it
work with the current version?
We're doing this as a school project and it would be a shame if it didn't work.

**Comment by bradytheinventor** [comment]
I mean I guess I don't know, you wouldn't know if something's broken without testing. It's probably completely fine to update to Python 3, but since it's an old project I don't really want to test changes right now.

If you're making your own version as a project, why don't you fork the repository? Then you have complete control over the code and can update to Python 3, add your own patterns and sequences, and generally do whatever you want with it.

**Comment by manuelp73** [comment]
OK, then if there are conflicts with my repository, maybe I will fix them and point to my repository.

**Pull request closed without merging**
